version: '3'

includes:
  addDigits: ./cmd/algorithm/addDigits/

tasks:
  run:
    cmds:
      - cmd: echo '111'
        ignore_error: true
      - task: addDigits:test
#      - cmd: go run .
#        ignore_error: true
    silent: false
    dir: ./
  helper:
    - cmd: sleep 1 ; echo '222'
  test:
    cmds:
      - sleep 1 ; echo 'AAA'
    deps: [helper, run]


# 執行task test
# 功能： https://taskfile.dev/usage/